In [2]:
print("Hello World")


Hello World


#### Move all the zeros at the end (without using for loop)

In [ ]:
print("Move all zeros to end (without loop)")
import numpy as np

arr1 = np.array([1, 0, 2, 0, 3, 0])
result = np.concatenate([arr1[arr1 != 0], arr1[arr1 == 0]])
print(result)
    

#### Find duplicate elements, unique and count the number of every element.

In [3]:
import numpy as np

print("Find duplicate Element")
arr2 = np.array([1,2,3,1,4,3])
unique, counts = np.unique(arr2, return_counts=True)
duplicates = unique[counts>1]
print(f"Unique element - {unique}, {counts}, {duplicates}")

Find duplicate Element
Unique element - [1 2 3 4], [2 1 2 1], [1 3]


In [7]:
arr4 = np.array([40, 50, 60, 70, 80])
normalized = (arr4 - np.mean(arr4)) // (np.std(arr4))
print(normalized)
                    

[-2. -1.  0.  0.  1.]


In [11]:
print("Row wise Sum of 2D array")
arr5 = np.array([[1,2], [3,4]])
row_sum = np.sum(arr5, axis=1)
print("Row sum :- ", row_sum)

Row sum :-  [3 7]


In [17]:
print("Marix multiplication using numpy")
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(f"Before multiplication :- \n {a}, \n {b}")

matrix_multi = np.dot(a, b)
print(f"After multiplication : \n {matrix_multi}")

Marix multiplication using numpy
Before multiplication :- 
 [[1 2]
 [3 4]], 
 [[5 6]
 [7 8]]
After multiplication : 
 [[19 22]
 [43 50]]


In [20]:
print("Top N element")
arr6 = np.array([20, 40, 10, 50, 32, 43])
top2 = np.sort(arr6)[-2:]
first2 = np.sort(arr6)[0:2]
print("Top 2 element :- ", top2)
print("First 2 element :- ", first2)


Top N element
Top 2 element :-  [43 50]
First 2 element :-  [10 20]


In [ ]:
print("Replace the value in array")
arr7 = np.array([10, 23, 8, 5, 90, 43])

print("After replace value :- ", np.where(arr7 > 20, 1, 0))
reverse = arr7[::-1]

print("Reverse array :- ", reverse)

Replace the value in array
After replace value :-  [0 1 0 0 1 1]
Reverse array :-  [43 90  5  8 23 10]


In [38]:
print("Missing number in array")
arr8 = np.array([1, 2, 3, 5, 6])

# "For numbers range from 1 to N use below method to find n"
n = np.max(arr8)

# if numbers range is from 0 to N then use n = len(arr)
missing_no = n*(n+1)//2 - np.sum(arr8)

print(missing_no)

Missing number in array
4


In [50]:
# print the identity matrix
arr9 = np.identity(3)
print("Identity matrix :- \n",arr9)


# convert this 1D -> 2D
arr10 = np.array([1,2,3,4,5,6])
arr11 = arr10.reshape(2, 3)
print("\n\n 2D array :- \n", arr11)

# Convert 2D -> 1D array
two_one = arr11.flatten()
print("\n2D array to 1D array :- \n", two_one)


Identity matrix :- 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 2D array :- 
 [[1 2 3]
 [4 5 6]]

2D array to 1D array :- 
 [1 2 3 4 5 6]


In [5]:
# find count occurrences and interaction between two array
import numpy as np

arr10 = np.array([1,2,3,4,5,6])
arr11 = arr10.reshape(2, 3)
two_one = arr11.flatten()
print("Count Occurences :- ", np.bincount(two_one))

# find the interaction between two arrays
arr7 = np.array([10, 23, 8, 5, 90, 43])
arr8 = np.array([1, 2, 3, 5, 6])
print("\nInteraction of two arrays :- ", np.intersect1d(arr7, arr8))

Count Occurences :-  [0 1 1 1 1 1 1]

Interaction of two arrays :-  [5]


#### Find Min. Max, and Mean

In [6]:

arr = np.array([4, 7, 1, 9, 3])
print("Max:", arr.max())
print("Min:", arr.min())
print("Mean:", arr.mean())
print("Std:", arr.std())


Max: 9
Min: 1
Mean: 4.8
Std: 2.85657137141714


#### Matrix Multiplication

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

C = np.dot(A, B)
print(C)

[[22 28]
 [49 64]]
